version: '3.1'
name: trustroute

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - NEO4J_AUTH=neo4j/12345678
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
