development:
  url: neo4j://localhost:7687
  username: neo4j
  password: '12345678'
  encryption: false

test:
  url: neo4j://localhost:7688
  username: neo4j
  password: '12345678'
  encryption: false